pipeline:
  name: baseline-implementation
  stages:
    - Checkout
    - Install
    - Lint
    - Unit Tests
    - Contract Tests
    - Integration Smoke
    - Security Scan
  notes: |
    This pipeline is a skeleton for local CI run or Jenkins. It runs lint, unit, contract and a placeholder for integration smoke tests.
